title: Content page
preset: page
files: false
fields:
    layout:
        label: Layout
        type: layout
        layouts:
            - "1/1"
            - "1/2, 1/2"
            - "1/4, 3/4"
            - "3/4, 1/4"
            - "1/2, 1/4, 1/4"
            - "1/4, 1/2, 1/4"
            - "1/4, 1/4, 1/2"
            - "1/4, 1/4, 1/4, 1/4"
